### ISSUE TITLE
httpserver.nim is missing

### ISSUE THREAD

**Issue by whydee86** [d4rckh/nimc2#2]
![image](https://user-images.githubusercontent.com/43274863/171373006-ad2ed602-23b0-485c-9abd-05d837b78783.png)

**Comment by d4rckh** [comment]
did not mean to make that file public until i finish the client itself. fix it now in https://github.com/d4rckh/nimc2/commit/ce85500dc67b461be85fd04d3e9d7e9a9a6f2058
