### ISSUE TITLE
[Cannot Open File : ws]

### ISSUE THREAD

**Issue by xelemental** [d4rckh/nimc2#4]
Hi d4rckh,

Good work on the nim c2. Can you help me with this issue, after running `nimble install` that is : `/root/nimc2/src/server/types.nim(1, 61) Error: cannot open file: ws` . Looking forward to your help! 

![image](https://user-images.githubusercontent.com/49472311/173530513-93b53b5e-2b4b-47ec-bb52-816352602401.png)

Thank You 😄

**Comment by d4rckh** [comment]
Oops, looks like I forgot to add ws in the nimble file. This is the reason it doesn't get installed using `nimble install`. You can manually install it using `nimble install ws` and the issue should be gone :)

**Comment by xelemental** [comment]
Thanks mate! Cheers 🍷
